-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 17:18:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema stretto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stretto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stretto` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `stretto`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL DEFAULT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`instruments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `instrument` VARCHAR(128) NULL DEFAULT NULL,
  `list_order` INT NULL DEFAULT NULL,
  `id_group` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_group`),
  INDEX `fk_instrument_group1_idx` (`id_group` ASC),
  CONSTRAINT `fk_instrument_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `stretto`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(128) NULL DEFAULT NULL,
  `lastname` VARCHAR(128) NULL DEFAULT NULL,
  `address` VARCHAR(128) NULL DEFAULT NULL,
  `postcode` INT(11) NULL DEFAULT NULL,
  `city` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `phone1` VARCHAR(32) NULL DEFAULT NULL,
  `phone2` VARCHAR(32) NULL DEFAULT NULL,
  `phone3` VARCHAR(32) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0 = sluttet\n1 = medlem\n2 = vikar\n3 = engasjert (fast)\n4 = engasjert (prosjekt)',
  `direction` INT(11) NULL DEFAULT NULL COMMENT '0 = aktiv\n1 = kan ikke bære stoler\n2 = fritatt',
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `id_instrument` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_instrument`),
  INDEX `fk_person_instrument1_idx` (`id_instrument` ASC),
  CONSTRAINT `fk_person_instrument1`
    FOREIGN KEY (`id_instrument`)
    REFERENCES `stretto`.`instruments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `semester` CHAR(1) NULL,
  `year` INT UNSIGNED NULL,
  `id_def_responsible` INT UNSIGNED NOT NULL,
  `info` TEXT NULL,
  `direction` TEXT NULL,
  `status` INT NULL,
  `deadline` TIMESTAMP NULL,
  `tutti` INT NULL,
  PRIMARY KEY (`id`, `id_def_responsible`),
  INDEX `fk_project_person1_idx` (`id_def_responsible` ASC),
  CONSTRAINT `fk_project_person1`
    FOREIGN KEY (`id_def_responsible`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `address` VARCHAR(128) NULL,
  `url` VARCHAR(256) NULL,
  `contact` TEXT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL,
  `time` VARCHAR(45) NULL,
  `tsort` INT NULL,
  `event` INT NULL,
  `id_location` INT UNSIGNED NOT NULL,
  `id_project` INT UNSIGNED NOT NULL,
  `id_responsible` INT UNSIGNED NOT NULL,
  `location` VARCHAR(128) NULL,
  `responsible` VARCHAR(128) NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`, `id_project`, `id_location`, `id_responsible`),
  INDEX `fk_plan_location1_idx` (`id_location` ASC),
  INDEX `fk_plan_project1_idx` (`id_project` ASC),
  INDEX `fk_plan_person1_idx` (`id_responsible` ASC),
  CONSTRAINT `fk_plan_location1`
    FOREIGN KEY (`id_location`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_person1`
    FOREIGN KEY (`id_responsible`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ts` TIMESTAMP NULL,
  `status` INT NULL,
  `comment` TEXT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_person`),
  INDEX `fk_record_person_idx` (`id_person` ASC),
  CONSTRAINT `fk_record_person`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`concert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`concert` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ts` TIMESTAMP NULL,
  `id_project` INT UNSIGNED NOT NULL,
  `id_location` INT UNSIGNED NOT NULL,
  `text` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concert_project1_idx` (`id_project` ASC),
  INDEX `fk_concert_location1_idx` (`id_location` ASC),
  CONSTRAINT `fk_concert_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concert_location1`
    FOREIGN KEY (`id_location`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_project` INT UNSIGNED NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_project1_idx` (`id_project` ASC),
  CONSTRAINT `fk_feedback_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrumentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrumentation` (
  `id_project` INT UNSIGNED NOT NULL,
  `id_instruments` INT UNSIGNED NOT NULL,
  `number` VARCHAR(10) NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id_project`, `id_instruments`),
  CONSTRAINT `fk_instrumentation_instruments1`
    FOREIGN KEY (`id_project`)
    REFERENCES `stretto`.`instruments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrumentation_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `stretto` ;

-- -----------------------------------------------------
-- Table `stretto`.`contingent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`contingent` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ts` TIMESTAMP NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_person`),
  INDEX `fk_Contingent_person1_idx` (`id_person` ASC),
  CONSTRAINT `fk_Contingent_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`absence` (
  `id_plan` INT UNSIGNED NOT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_plan`, `id_person`),
  INDEX `fk_absence_person1_idx` (`id_person` ASC),
  CONSTRAINT `fk_absence_plan1`
    FOREIGN KEY (`id_plan`)
    REFERENCES `mydb`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_absence_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`view` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `access` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`auth_group` (
  `id_group` INT UNSIGNED NOT NULL,
  `id_view` INT UNSIGNED NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_group`, `id_view`),
  INDEX `fk_auth_group_view1_idx` (`id_view` ASC),
  CONSTRAINT `fk_auth_group_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `stretto`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_group_view1`
    FOREIGN KEY (`id_view`)
    REFERENCES `stretto`.`view` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`auth_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`auth_person` (
  `id_view` INT UNSIGNED NOT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_view`, `id_person`),
  INDEX `fk_auth_person_person1_idx` (`id_person` ASC),
  CONSTRAINT `fk_auth_person_view1`
    FOREIGN KEY (`id_view`)
    REFERENCES `stretto`.`view` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_person_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`direction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`direction` (
  `id_person` INT UNSIGNED NOT NULL,
  `id_plan` INT UNSIGNED NOT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_person`, `id_plan`),
  INDEX `fk_direction_plan1_idx` (`id_plan` ASC),
  CONSTRAINT `fk_direction_plan1`
    FOREIGN KEY (`id_plan`)
    REFERENCES `mydb`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direction_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`member` (
  `id_group` INT UNSIGNED NOT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_group`, `id_person`),
  INDEX `fk_member_person1_idx` (`id_person` ASC),
  CONSTRAINT `fk_member_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `stretto`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`repository` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_oso` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(128) NULL DEFAULT '',
  `work` VARCHAR(128) NULL DEFAULT '',
  `firstname` VARCHAR(128) NULL DEFAULT NULL,
  `lastname` VARCHAR(128) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`music` (
  `id_repository` INT UNSIGNED NOT NULL,
  `id_project` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_repository`, `id_project`),
  INDEX `fk_music_project1_idx` (`id_project` ASC),
  CONSTRAINT `fk_music_repository1`
    FOREIGN KEY (`id_repository`)
    REFERENCES `stretto`.`repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_music_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`participant` (
  `id_person` INT UNSIGNED NOT NULL,
  `id_project` INT UNSIGNED NOT NULL,
  `stat_self` INT(11) NULL DEFAULT NULL,
  `ts_self` TIMESTAMP NULL DEFAULT NULL,
  `comment_self` TEXT NULL DEFAULT NULL,
  `stat_reg` INT(11) NULL DEFAULT NULL,
  `ts_reg` TIMESTAMP NULL DEFAULT NULL,
  `comment_reg` TEXT NULL DEFAULT NULL,
  `stat_req` INT(11) NULL DEFAULT NULL,
  `ts_req` TIMESTAMP NULL DEFAULT NULL,
  `comment_req` TEXT NULL DEFAULT NULL,
  `stat_final` INT(11) NULL DEFAULT NULL,
  `ts_final` TIMESTAMP NULL DEFAULT NULL,
  `comment_final` TEXT NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_person`, `id_project`),
  INDEX `fk_participant_project1_idx` (`id_project` ASC),
  CONSTRAINT `fk_participant_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stretto`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stretto`.`shift` (
  `id_project` INT UNSIGNED NOT NULL,
  `id_person` INT UNSIGNED NOT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_project`, `id_person`),
  INDEX `fk_shift_person1_idx` (`id_person` ASC),
  CONSTRAINT `fk_shift_project1`
    FOREIGN KEY (`id_project`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shift_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `stretto`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
